apiVersion: v1
items:
  - apiVersion: gateway.networking.k8s.io/v1
    kind: Gateway
    metadata:
      annotations:
        networking.istio.io/service-type: NodePort
      labels:
        istio.io/rev: openshift-gateway
      name: default-gateway
      namespace: openshift-ingress
    spec:
      gatewayClassName: openshift-default
      listeners:
        - allowedRoutes:
            namespaces:
              from: All
          hostname: '*.gw.mydomain.com'
          name: https
          port: 443
          protocol: HTTPS
          tls:
            certificateRefs:
              - group: ""
                kind: Secret
                name: ingress-controller-cert
            mode: Terminate
kind: List
metadata: {}
